name: "DÃ©ploy Client to Vercel"
on:
  push:
    tags:
      - "*"
  pull_request:
    branches: ["main"]

jobs:
  # Lint-commits
  lints-commit:
    name: Check frontend lint commit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install commitlint
        run: | 
          npm install --save-dev @commitlint/cli @commitlint/config-conventional && \
          echo "export default { extends: ['@commitlint/config-conventional'] };" > commitlint.config.mjs
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      # Check with Pull Request...
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from origin/main --to HEAD

  security-scan-npm:
    name: Check frontend security-scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/client
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: lts/*

        - name: Install dependencies
          run: npm ci

        - name: Npm Audit
          run: npm audit fix --audit-level=high
        - name: Notify discord
          uses: th0th/notify-discord@v0.4.1
          if: ${{ always() }}
          env:
            DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
            GITHUB_ACTOR: ${{ github.actor }}
            GITHUB_JOB_NAME: "security-scan-npm"
            GITHUB_JOB_STATUS: ${{ job.status }}
  # Deploy Frontend to Vercel
  deploy-frontend:
    name: Check frontend code quality and Deploy to Vercel
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/client
    needs: security-scan-npm
    if: github.event_name == 'push'
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: lts/*

        - name: Install dependencies
          run: npm ci
        
        - name: Check code quality with ESLint
          run: npm run lint

        - name: Run Frontend Tests with Coverage
          run: npm run test --coverage.enabled true
        - name: 'Report Coverage'
          uses: actions/upload-artifact@v4
          with:
            name: coverage-report-frontend
            path: packages/client/coverage/

        - name: Deploy to Vercel
          uses: amondnet/vercel-action@v25
          with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }}
            vercel-args: '--prod'
            working-directory: ./packages/client
            vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
            vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        - name: Notify discord
          uses: th0th/notify-discord@v0.4.1
          if: ${{ always() }}
          env:
            DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
            GITHUB_ACTOR: ${{ github.actor }}
            GITHUB_JOB_NAME: "deploy-frontend"
            GITHUB_JOB_STATUS: ${{ job.status }}