name: "DÃ©ploy Client to Vercel"
on:
  push:
    branches:
      - main
      - dancodeur
  pull_request:
    branches:
      - main

jobs:
  # Lint-commits
  lints-commit:
    name: Check frontend lint commit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install commitlint
        run: npm install -D @commitlint/cli @commitlint/config-conventional
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      # Check with Pull Request...
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      # Discord Notification
      - name: Jobs (Check frontend lint commit)
        uses: tenzin1308/discord-notification@v1.0.0
        with:
          discord-webhook-url: ${{secrets.WEBHOOKS_URL}}

  security-scan-npm:
    name: Check frontend security-scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/client
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: lts/*

        - name: Install dependencies
          run: npm ci

        - name: Npm Audit
          run: npm audit fix --audit-level=high
        # Discord Notification
        - name: Jobs (lints-commit)
          uses: tenzin1308/discord-notification@v1.0.0
          with:
            discord-webhook-url: ${{secrets.WEBHOOKS_URL}}

  # Deploy Frontend to Vercel
  deploy-frontend:
    name: Check frontend code quality and Deploy to Vercel
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/client
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: lts/*

        - name: Install dependencies
          run: npm ci
        
        - name: Check code quality with ESLint
          run: npm run lint

        - name: Run Frontend Tests with Coverage
          run: npm run test --coverage.enabled true
        - name: 'Report Coverage'
          uses: actions/upload-artifact@v4
          with:
            name: coverage-report-frontend
            path: packages/client/coverage/

        - name: Deploy to Vercel
          uses: amondnet/vercel-action@v25
          with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }}
            vercel-args: '--prod'
            working-directory: ./packages/client
            vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
            vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        # Discord Notification
        - name: Jobs (deploy-frontend)
          uses: tenzin1308/discord-notification@v1.0.0
          with:
            discord-webhook-url: ${{secrets.WEBHOOKS_URL}}