name: "DÃ©ploy Client to Vercel"
on:
  push:
    branches:
      - main
      - dancodeur

jobs:
  #Deploy Frontend to Vercel
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/client
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: lts/*

        - name: Install dependencies
          run: npm ci
        
        - name: Check code quality with ESLint
          run: npm run lint

        - name: Run Frontend Tests with Coverage
          run: npm run test --coverage.enabled true
        - name: 'Report Coverage'
          uses: actions/upload-artifact@v4
          with:
            name: coverage-report-frontend
            path: packages/client/coverage/

        - name: Deploy to Vercel
          uses: amondnet/vercel-action@v25
          with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }}
            vercel-args: '--prod'
            working-directory: ./packages/client
            vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
            vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}