name: server-ci
on: [push, pull_request, release]
jobs:
  security-scan-npm:
    name: Security Scan NPM
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm audit fix --audit-level=high

  test-unit:
    name: Unit Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: packages/server/coverage/
          retention-days: 1

  coverage:
    name: Coverage Backend
    runs-on: ubuntu-latest
    needs: test-unit
    if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: ./packages/server
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: packages/server/coverage/

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ./packages/server
          json-summary-path: 'coverage/coverage-summary.json'
          json-final-path: 'coverage/coverage-final.json'
          vite-config-path: 'vitest.config.ts'
          github-token: ${{ secrets.COVERAGE_TOKEN }}

  build-docker:
    name: Build Docker Image
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    environment: production
    steps: 
      - uses: actions/checkout@v4

      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push production image
        uses: docker/build-push-action@v6
        with:
          context: ./packages/server
          file: Dockerfile
          push:  github.event_name == 'release'
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache