name: server-ci
on:
  push:
    branches: ["kyllian"]
  pull_request:
    branches: ["main"]

jobs:
  security-scan-npm:
    name: Security Scan NPM
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm audit fix --audit-level=high

  test-unit:
    name: Unit Test Backend
    runs-on: ubuntu-latest
    needs: security-scan-npm
    defaults:
      run:
        working-directory: ./packages/server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: packages/server/coverage/
          retention-days: 1

  coverage:
    name: Coverage Backend
    runs-on: ubuntu-latest
    needs: test-unit
    if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: ./packages/server
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: packages/server/coverage/

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ./packages/server
          json-summary-path: 'coverage/coverage-summary.json'
          json-final-path: 'coverage/coverage-final.json'
          vite-config-path: 'vitest.config.ts'
          github-token: ${{ secrets.COVERAGE_TOKEN }}

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}
          tags: |
            type=ref,event=tag

      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push production image
        uses: docker/build-push-action@v6
        with:
          context: ./packages/server
          file: ./packages/server/Dockerfile
          push:  ${{ github.event_name == 'push' }}
          platforms: linux/amd64
          outputs: ${{ github.event_name == 'pull_request' && 'type=docker,dest=/tmp/image.tar' || '' }}
          tags: ${{ steps.meta.outputs.tags }}
      
      - name: Upload artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/image.tar
          retention-days: 1

  security-scan-docker:
    name: Security scan for Docker Image with Trivy
    needs: build-docker
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          input: /tmp/image.tar 
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
  
  deploy-backend:
    name: Deploy Backend to Render
    needs: build-docker
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      renderId: ${{ steps.trigger.outputs.renderId }}

    steps:
      - name: Trigger Render Deploy Hook
        id: trigger
        env:
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          API_KEY: ${{ secrets.RENDER_API_KEY }}
          IMAGE_URL: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:${{ github.ref_name }}
        run: |
          set -e
          echo "üöÄ D√©clenchement du d√©ploiement via API..."
          
          # 1. On utilise l'API POST (et pas le Hook) pour avoir une r√©ponse JSON propre
          # On force l'image URL dans le body de la requ√™te
          RESPONSE=$(curl "${{ secrets.RENDER_DEPLOY_HOOK }}&imgURL=${IMAGE_URL}")

          # 2. V√©rification que la r√©ponse contient bien un ID
          RENDER_ID=$(echo "$RESPONSE" | jq -r '.deploy.id')
          
          if [[ "$RENDER_ID" == "null" || -z "$RENDER_ID" ]]; then
            echo "‚ùå Erreur: Pas d'ID re√ßu. R√©ponse API:"
            echo "$RESPONSE"
            exit 1
          fi

          echo "‚úÖ ID r√©cup√©r√© : $RENDER_ID"
          echo "renderId=$RENDER_ID" >> "$GITHUB_OUTPUT"

  smoke-test:
    name: Check if Docker Image is live
    needs: deploy-backend
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render API to retrieve deploy status
        env:
          RENDER_ID: ${{needs.deploy-backend.outputs.renderId}}
        run: |
          set -e
          echo "üîç Suivi du d√©ploiement ID: ${RENDER_ID}"
          
          # Boucle infinie (avec timeout implicite de GitHub Actions ~6h)
          while true; do
            STATUS=$(curl -s --request GET \
              --url "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys/${RENDER_ID}" \
              --header "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" | jq -r ".status")
            
            echo "Statut actuel : $STATUS"

            if [ "$STATUS" == "live" ]; then
              echo "‚úÖ Le service est en ligne (live) !"
              exit 0
            fi

            if [[ "$STATUS" == "build_failed" || "$STATUS" == "update_failed" || "$STATUS" == "canceled" ]]; then
              echo "‚ùå Le d√©ploiement a √©chou√©."
              exit 1
            fi

            # Attendre 10 secondes avant de rev√©rifier
            sleep 10
          done

      - name: Notify discord
        uses: th0th/notify-discord@v0.4.1
        if: ${{ success() }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_JOB_NAME: "Successful deployment"
          GITHUB_JOB_STATUS: ${{ job.status }}

          